### ISSUE TITLE
[affirm]: Add submission thought of during lunges

### ISSUE THREAD

**Issue by marination** [gavindsouza/devly-affirmations#3]
### Affirmation

My mind's stack is not overflowing

### Author

maricadsouza221197@gmail.com

**Comment by gavindsouza** [comment]
LGTM

**Comment by gavindsouza** [comment]
LGTM

**Comment by gavindsouza** [comment]
LGTM

**Comment by gavindsouza** [comment]
LGTM

**Comment by gavindsouza** [comment]
LGTM

**Comment by gavindsouza** [comment]
There were issues handling quotes in the submissions which have been fixed now. Thanks for helping make the contribution pipeline better 😄.

Your submission is added via https://github.com/gavindsouza/devly-affirmations/commit/08749ccc51a0f5d333bfbffeb87518b9fe36c36e 🥳
